import { ScanLineIcon } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';

export default function ScannerView() {
  return (
    <View style={styles.overlay}>
      <View style={styles.targetBox}>
        <ScanLineIcon color="rgba(255, 255, 255, 0.7)" size={120} strokeWidth={1} />
      </View>
      <Text style={styles.instructionText}>Frame the QR Code generated by the site</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  targetBox: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.8)',
    borderRadius: 20,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 100,
  },
  instructionText: {
    position: 'absolute',
    bottom: 60,
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
});
