import { render, screen } from '@testing-library/react-native';
import React from 'react';
import ScannerView from './ScannerView';

describe('ScannerView Component', () => {
  test('renders the instruction text correctly', async () => {
    await render(<ScannerView />);

    const instruction = screen.getByText('Frame the QR Code generated by the site');
    expect(instruction).toBeOnTheScreen();
  });

  test('renders the scanner overlay without crashing', async () => {
    const { toJSON } = await render(<ScannerView />);
    expect(toJSON()).toBeTruthy();
  });
});
