/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AuthResponseDto, UserCreateDto } from '../models/index';
import {
  AuthResponseDtoFromJSON,
  AuthResponseDtoToJSON,
  UserCreateDtoFromJSON,
  UserCreateDtoToJSON,
} from '../models/index';

export interface AuthControllerRegisterRequest {
  userCreateDto: UserCreateDto;
}

export interface AuthControllerSignInRequest {
  userCreateDto: UserCreateDto;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for authControllerRegister without sending the request
   */
  async authControllerRegisterRequestOpts(
    requestParameters: AuthControllerRegisterRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userCreateDto'] == null) {
      throw new runtime.RequiredError(
        'userCreateDto',
        'Required parameter "userCreateDto" was null or undefined when calling authControllerRegister().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/register`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: UserCreateDtoToJSON(requestParameters['userCreateDto']),
    };
  }

  /**
   * Register a new user and return the JWT immediately
   */
  async authControllerRegisterRaw(
    requestParameters: AuthControllerRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponseDto>> {
    const requestOptions = await this.authControllerRegisterRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseDtoFromJSON(jsonValue));
  }

  /**
   * Register a new user and return the JWT immediately
   */
  async authControllerRegister(
    requestParameters: AuthControllerRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponseDto> {
    const response = await this.authControllerRegisterRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for authControllerSignIn without sending the request
   */
  async authControllerSignInRequestOpts(
    requestParameters: AuthControllerSignInRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userCreateDto'] == null) {
      throw new runtime.RequiredError(
        'userCreateDto',
        'Required parameter "userCreateDto" was null or undefined when calling authControllerSignIn().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/login`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: UserCreateDtoToJSON(requestParameters['userCreateDto']),
    };
  }

  /**
   * Log in and return the JWT token
   */
  async authControllerSignInRaw(
    requestParameters: AuthControllerSignInRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponseDto>> {
    const requestOptions = await this.authControllerSignInRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseDtoFromJSON(jsonValue));
  }

  /**
   * Log in and return the JWT token
   */
  async authControllerSignIn(
    requestParameters: AuthControllerSignInRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponseDto> {
    const response = await this.authControllerSignInRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
