/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  PasswordCreateDto,
  PasswordResponseDto,
  PasswordUpdateDto,
  PasswordsControllerUpdateFavoriteRequest,
} from '../models/index';
import {
  PasswordCreateDtoFromJSON,
  PasswordCreateDtoToJSON,
  PasswordResponseDtoFromJSON,
  PasswordResponseDtoToJSON,
  PasswordUpdateDtoFromJSON,
  PasswordUpdateDtoToJSON,
  PasswordsControllerUpdateFavoriteRequestFromJSON,
  PasswordsControllerUpdateFavoriteRequestToJSON,
} from '../models/index';

export interface PasswordsControllerCreateOneRequest {
  passwordCreateDto: PasswordCreateDto;
}

export interface PasswordsControllerDeleteOneRequest {
  id: string;
}

export interface PasswordsControllerFindOneRequest {
  id: string;
}

export interface PasswordsControllerUpdateFavoriteOperationRequest {
  id: string;
  passwordsControllerUpdateFavoriteRequest: PasswordsControllerUpdateFavoriteRequest;
}

export interface PasswordsControllerUpdateOneRequest {
  id: string;
  passwordUpdateDto: PasswordUpdateDto;
}

/**
 *
 */
export class PasswordsApi extends runtime.BaseAPI {
  /**
   * Creates request options for passwordsControllerCreateOne without sending the request
   */
  async passwordsControllerCreateOneRequestOpts(
    requestParameters: PasswordsControllerCreateOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['passwordCreateDto'] == null) {
      throw new runtime.RequiredError(
        'passwordCreateDto',
        'Required parameter "passwordCreateDto" was null or undefined when calling passwordsControllerCreateOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: PasswordCreateDtoToJSON(requestParameters['passwordCreateDto']),
    };
  }

  /**
   * Create a new password
   */
  async passwordsControllerCreateOneRaw(
    requestParameters: PasswordsControllerCreateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PasswordResponseDto>> {
    const requestOptions = await this.passwordsControllerCreateOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PasswordResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Create a new password
   */
  async passwordsControllerCreateOne(
    requestParameters: PasswordsControllerCreateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PasswordResponseDto> {
    const response = await this.passwordsControllerCreateOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerDeleteOne without sending the request
   */
  async passwordsControllerDeleteOneRequestOpts(
    requestParameters: PasswordsControllerDeleteOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling passwordsControllerDeleteOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a password
   */
  async passwordsControllerDeleteOneRaw(
    requestParameters: PasswordsControllerDeleteOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PasswordResponseDto>> {
    const requestOptions = await this.passwordsControllerDeleteOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PasswordResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Delete a password
   */
  async passwordsControllerDeleteOne(
    requestParameters: PasswordsControllerDeleteOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PasswordResponseDto> {
    const response = await this.passwordsControllerDeleteOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerFindAll without sending the request
   */
  async passwordsControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all user passwords
   */
  async passwordsControllerFindAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PasswordResponseDto>>> {
    const requestOptions = await this.passwordsControllerFindAllRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PasswordResponseDtoFromJSON),
    );
  }

  /**
   * Returns all user passwords
   */
  async passwordsControllerFindAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PasswordResponseDto>> {
    const response = await this.passwordsControllerFindAllRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerFindFavorites without sending the request
   */
  async passwordsControllerFindFavoritesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords/favorites`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns favorite passwords only
   */
  async passwordsControllerFindFavoritesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PasswordResponseDto>>> {
    const requestOptions = await this.passwordsControllerFindFavoritesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PasswordResponseDtoFromJSON),
    );
  }

  /**
   * Returns favorite passwords only
   */
  async passwordsControllerFindFavorites(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PasswordResponseDto>> {
    const response = await this.passwordsControllerFindFavoritesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerFindOne without sending the request
   */
  async passwordsControllerFindOneRequestOpts(
    requestParameters: PasswordsControllerFindOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling passwordsControllerFindOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a single password via ID
   */
  async passwordsControllerFindOneRaw(
    requestParameters: PasswordsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PasswordResponseDto>> {
    const requestOptions = await this.passwordsControllerFindOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PasswordResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Returns a single password via ID
   */
  async passwordsControllerFindOne(
    requestParameters: PasswordsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PasswordResponseDto> {
    const response = await this.passwordsControllerFindOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerUpdateFavorite without sending the request
   */
  async passwordsControllerUpdateFavoriteRequestOpts(
    requestParameters: PasswordsControllerUpdateFavoriteOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling passwordsControllerUpdateFavorite().',
      );
    }

    if (requestParameters['passwordsControllerUpdateFavoriteRequest'] == null) {
      throw new runtime.RequiredError(
        'passwordsControllerUpdateFavoriteRequest',
        'Required parameter "passwordsControllerUpdateFavoriteRequest" was null or undefined when calling passwordsControllerUpdateFavorite().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords/{id}/favorite`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: PasswordsControllerUpdateFavoriteRequestToJSON(
        requestParameters['passwordsControllerUpdateFavoriteRequest'],
      ),
    };
  }

  /**
   * Change the favorite state of a passowrd
   */
  async passwordsControllerUpdateFavoriteRaw(
    requestParameters: PasswordsControllerUpdateFavoriteOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PasswordResponseDto>> {
    const requestOptions =
      await this.passwordsControllerUpdateFavoriteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PasswordResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Change the favorite state of a passowrd
   */
  async passwordsControllerUpdateFavorite(
    requestParameters: PasswordsControllerUpdateFavoriteOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PasswordResponseDto> {
    const response = await this.passwordsControllerUpdateFavoriteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for passwordsControllerUpdateOne without sending the request
   */
  async passwordsControllerUpdateOneRequestOpts(
    requestParameters: PasswordsControllerUpdateOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling passwordsControllerUpdateOne().',
      );
    }

    if (requestParameters['passwordUpdateDto'] == null) {
      throw new runtime.RequiredError(
        'passwordUpdateDto',
        'Required parameter "passwordUpdateDto" was null or undefined when calling passwordsControllerUpdateOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/passwords/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: PasswordUpdateDtoToJSON(requestParameters['passwordUpdateDto']),
    };
  }

  /**
   * Update completely a password
   */
  async passwordsControllerUpdateOneRaw(
    requestParameters: PasswordsControllerUpdateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PasswordResponseDto>> {
    const requestOptions = await this.passwordsControllerUpdateOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PasswordResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Update completely a password
   */
  async passwordsControllerUpdateOne(
    requestParameters: PasswordsControllerUpdateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PasswordResponseDto> {
    const response = await this.passwordsControllerUpdateOneRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
