/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EventSessionDto,
  UserCreateDto,
  UserResponseDto,
  UserUpdateDto,
} from '../models/index';
import {
    EventSessionDtoFromJSON,
    EventSessionDtoToJSON,
    UserCreateDtoFromJSON,
    UserCreateDtoToJSON,
    UserResponseDtoFromJSON,
    UserResponseDtoToJSON,
    UserUpdateDtoFromJSON,
    UserUpdateDtoToJSON,
} from '../models/index';

export interface UsersControllerCreateOneRequest {
    userCreateDto: UserCreateDto;
}

export interface UsersControllerUpdateMeRequest {
    userUpdateDto: UserUpdateDto;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersControllerActiveSessions without sending the request
     */
    async usersControllerActiveSessionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/session`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current user\'s sessions
     */
    async usersControllerActiveSessionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventSessionDto>>> {
        const requestOptions = await this.usersControllerActiveSessionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventSessionDtoFromJSON));
    }

    /**
     * Returns the current user\'s sessions
     */
    async usersControllerActiveSessions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventSessionDto>> {
        const response = await this.usersControllerActiveSessionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersControllerCreateOne without sending the request
     */
    async usersControllerCreateOneRequestOpts(requestParameters: UsersControllerCreateOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userCreateDto'] == null) {
            throw new runtime.RequiredError(
                'userCreateDto',
                'Required parameter "userCreateDto" was null or undefined when calling usersControllerCreateOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateDtoToJSON(requestParameters['userCreateDto']),
        };
    }

    /**
     * Register a new user
     */
    async usersControllerCreateOneRaw(requestParameters: UsersControllerCreateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponseDto>> {
        const requestOptions = await this.usersControllerCreateOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Register a new user
     */
    async usersControllerCreateOne(requestParameters: UsersControllerCreateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponseDto> {
        const response = await this.usersControllerCreateOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersControllerDeleteMe without sending the request
     */
    async usersControllerDeleteMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/me`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the current user\'s profile
     */
    async usersControllerDeleteMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponseDto>> {
        const requestOptions = await this.usersControllerDeleteMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Delete the current user\'s profile
     */
    async usersControllerDeleteMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponseDto> {
        const response = await this.usersControllerDeleteMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersControllerFindMe without sending the request
     */
    async usersControllerFindMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current user\'s profile
     */
    async usersControllerFindMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponseDto>> {
        const requestOptions = await this.usersControllerFindMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns the current user\'s profile
     */
    async usersControllerFindMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponseDto> {
        const response = await this.usersControllerFindMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersControllerUpdateMe without sending the request
     */
    async usersControllerUpdateMeRequestOpts(requestParameters: UsersControllerUpdateMeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userUpdateDto'] == null) {
            throw new runtime.RequiredError(
                'userUpdateDto',
                'Required parameter "userUpdateDto" was null or undefined when calling usersControllerUpdateMe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/me`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateDtoToJSON(requestParameters['userUpdateDto']),
        };
    }

    /**
     * Update the current user\'s profile
     */
    async usersControllerUpdateMeRaw(requestParameters: UsersControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponseDto>> {
        const requestOptions = await this.usersControllerUpdateMeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update the current user\'s profile
     */
    async usersControllerUpdateMe(requestParameters: UsersControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponseDto> {
        const response = await this.usersControllerUpdateMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
