/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  PasswordResponseDto,
  VaultCreateDto,
  VaultResponseDto,
  VaultUpdateDto,
} from '../models/index';
import {
  PasswordResponseDtoFromJSON,
  PasswordResponseDtoToJSON,
  VaultCreateDtoFromJSON,
  VaultCreateDtoToJSON,
  VaultResponseDtoFromJSON,
  VaultResponseDtoToJSON,
  VaultUpdateDtoFromJSON,
  VaultUpdateDtoToJSON,
} from '../models/index';

export interface VaultsControllerCreateOneRequest {
  vaultCreateDto: VaultCreateDto;
}

export interface VaultsControllerDeleteOneRequest {
  id: string;
}

export interface VaultsControllerFindOneRequest {
  id: string;
}

export interface VaultsControllerFindVaultPasswordsRequest {
  vaultId: string;
}

export interface VaultsControllerUpdateOneRequest {
  id: string;
  vaultUpdateDto: VaultUpdateDto;
}

/**
 *
 */
export class VaultsApi extends runtime.BaseAPI {
  /**
   * Creates request options for vaultsControllerCreateOne without sending the request
   */
  async vaultsControllerCreateOneRequestOpts(
    requestParameters: VaultsControllerCreateOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['vaultCreateDto'] == null) {
      throw new runtime.RequiredError(
        'vaultCreateDto',
        'Required parameter "vaultCreateDto" was null or undefined when calling vaultsControllerCreateOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: VaultCreateDtoToJSON(requestParameters['vaultCreateDto']),
    };
  }

  /**
   * Create a new vault
   */
  async vaultsControllerCreateOneRaw(
    requestParameters: VaultsControllerCreateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VaultResponseDto>> {
    const requestOptions = await this.vaultsControllerCreateOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VaultResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Create a new vault
   */
  async vaultsControllerCreateOne(
    requestParameters: VaultsControllerCreateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VaultResponseDto> {
    const response = await this.vaultsControllerCreateOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for vaultsControllerDeleteOne without sending the request
   */
  async vaultsControllerDeleteOneRequestOpts(
    requestParameters: VaultsControllerDeleteOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling vaultsControllerDeleteOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a vault and its contents
   */
  async vaultsControllerDeleteOneRaw(
    requestParameters: VaultsControllerDeleteOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VaultResponseDto>> {
    const requestOptions = await this.vaultsControllerDeleteOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VaultResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Delete a vault and its contents
   */
  async vaultsControllerDeleteOne(
    requestParameters: VaultsControllerDeleteOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VaultResponseDto> {
    const response = await this.vaultsControllerDeleteOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for vaultsControllerFindAll without sending the request
   */
  async vaultsControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all user vaults
   */
  async vaultsControllerFindAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<VaultResponseDto>>> {
    const requestOptions = await this.vaultsControllerFindAllRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(VaultResponseDtoFromJSON),
    );
  }

  /**
   * Returns all user vaults
   */
  async vaultsControllerFindAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<VaultResponseDto>> {
    const response = await this.vaultsControllerFindAllRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for vaultsControllerFindOne without sending the request
   */
  async vaultsControllerFindOneRequestOpts(
    requestParameters: VaultsControllerFindOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling vaultsControllerFindOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Return a single vault by ID
   */
  async vaultsControllerFindOneRaw(
    requestParameters: VaultsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VaultResponseDto>> {
    const requestOptions = await this.vaultsControllerFindOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VaultResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Return a single vault by ID
   */
  async vaultsControllerFindOne(
    requestParameters: VaultsControllerFindOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VaultResponseDto> {
    const response = await this.vaultsControllerFindOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for vaultsControllerFindVaultPasswords without sending the request
   */
  async vaultsControllerFindVaultPasswordsRequestOpts(
    requestParameters: VaultsControllerFindVaultPasswordsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['vaultId'] == null) {
      throw new runtime.RequiredError(
        'vaultId',
        'Required parameter "vaultId" was null or undefined when calling vaultsControllerFindVaultPasswords().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults/{vaultId}/passwords`;
    urlPath = urlPath.replace(
      `{${'vaultId'}}`,
      encodeURIComponent(String(requestParameters['vaultId'])),
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all passwords contained in a specific vault
   */
  async vaultsControllerFindVaultPasswordsRaw(
    requestParameters: VaultsControllerFindVaultPasswordsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PasswordResponseDto>>> {
    const requestOptions =
      await this.vaultsControllerFindVaultPasswordsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PasswordResponseDtoFromJSON),
    );
  }

  /**
   * Returns all passwords contained in a specific vault
   */
  async vaultsControllerFindVaultPasswords(
    requestParameters: VaultsControllerFindVaultPasswordsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PasswordResponseDto>> {
    const response = await this.vaultsControllerFindVaultPasswordsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for vaultsControllerUpdateOne without sending the request
   */
  async vaultsControllerUpdateOneRequestOpts(
    requestParameters: VaultsControllerUpdateOneRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling vaultsControllerUpdateOne().',
      );
    }

    if (requestParameters['vaultUpdateDto'] == null) {
      throw new runtime.RequiredError(
        'vaultUpdateDto',
        'Required parameter "vaultUpdateDto" was null or undefined when calling vaultsControllerUpdateOne().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/vaults/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: VaultUpdateDtoToJSON(requestParameters['vaultUpdateDto']),
    };
  }

  /**
   * Update an existing vault
   */
  async vaultsControllerUpdateOneRaw(
    requestParameters: VaultsControllerUpdateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VaultResponseDto>> {
    const requestOptions = await this.vaultsControllerUpdateOneRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VaultResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Update an existing vault
   */
  async vaultsControllerUpdateOne(
    requestParameters: VaultsControllerUpdateOneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VaultResponseDto> {
    const response = await this.vaultsControllerUpdateOneRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
