/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventSessionDto
 */
export interface EventSessionDto {
    /**
     * 
     * @type {string}
     * @memberof EventSessionDto
     */
    socketId: string;
    /**
     * 
     * @type {string}
     * @memberof EventSessionDto
     */
    userAgent: string;
    /**
     * 
     * @type {string}
     * @memberof EventSessionDto
     */
    ip: string;
    /**
     * 
     * @type {Date}
     * @memberof EventSessionDto
     */
    connectedAt: Date;
}

/**
 * Check if a given object implements the EventSessionDto interface.
 */
export function instanceOfEventSessionDto(value: object): value is EventSessionDto {
    if (!('socketId' in value) || value['socketId'] === undefined) return false;
    if (!('userAgent' in value) || value['userAgent'] === undefined) return false;
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('connectedAt' in value) || value['connectedAt'] === undefined) return false;
    return true;
}

export function EventSessionDtoFromJSON(json: any): EventSessionDto {
    return EventSessionDtoFromJSONTyped(json, false);
}

export function EventSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'socketId': json['socketId'],
        'userAgent': json['userAgent'],
        'ip': json['ip'],
        'connectedAt': (new Date(json['connectedAt'])),
    };
}

export function EventSessionDtoToJSON(json: any): EventSessionDto {
    return EventSessionDtoToJSONTyped(json, false);
}

export function EventSessionDtoToJSONTyped(value?: EventSessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'socketId': value['socketId'],
        'userAgent': value['userAgent'],
        'ip': value['ip'],
        'connectedAt': value['connectedAt'].toISOString(),
    };
}

