/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordUpdateDto
 */
export interface PasswordUpdateDto {
<<<<<<< HEAD
    /**
     * Vault ID of the vault you belong to
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    vaultId?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    otpCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordUpdateDto
     */
    favorite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordUpdateDto
     */
    haveOtp?: boolean;
=======
  /**
   * Vault ID of the vault you belong to
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  vaultId?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  service?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordUpdateDto
   */
  otpCode?: string;
  /**
   *
   * @type {boolean}
   * @memberof PasswordUpdateDto
   */
  favorite?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PasswordUpdateDto
   */
  haveOtp?: boolean;
>>>>>>> dev
}

/**
 * Check if a given object implements the PasswordUpdateDto interface.
 */
export function instanceOfPasswordUpdateDto(value: object): value is PasswordUpdateDto {
  return true;
}

export function PasswordUpdateDtoFromJSON(json: any): PasswordUpdateDto {
  return PasswordUpdateDtoFromJSONTyped(json, false);
}

<<<<<<< HEAD
export function PasswordUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vaultId'] == null ? undefined : json['vaultId'],
        'service': json['service'] == null ? undefined : json['service'],
        'website': json['website'] == null ? undefined : json['website'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'otpCode': json['otpCode'] == null ? undefined : json['otpCode'],
        'favorite': json['favorite'] == null ? undefined : json['favorite'],
        'haveOtp': json['haveOtp'] == null ? undefined : json['haveOtp'],
    };
=======
export function PasswordUpdateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PasswordUpdateDto {
  if (json == null) {
    return json;
  }
  return {
    vaultId: json['vaultId'] == null ? undefined : json['vaultId'],
    service: json['service'] == null ? undefined : json['service'],
    website: json['website'] == null ? undefined : json['website'],
    username: json['username'] == null ? undefined : json['username'],
    password: json['password'] == null ? undefined : json['password'],
    otpCode: json['otpCode'] == null ? undefined : json['otpCode'],
    favorite: json['favorite'] == null ? undefined : json['favorite'],
    haveOtp: json['haveOtp'] == null ? undefined : json['haveOtp'],
  };
>>>>>>> dev
}

export function PasswordUpdateDtoToJSON(json: any): PasswordUpdateDto {
  return PasswordUpdateDtoToJSONTyped(json, false);
}

export function PasswordUpdateDtoToJSONTyped(
  value?: PasswordUpdateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

<<<<<<< HEAD
    return {
        
        'vaultId': value['vaultId'],
        'service': value['service'],
        'website': value['website'],
        'username': value['username'],
        'password': value['password'],
        'otpCode': value['otpCode'],
        'favorite': value['favorite'],
        'haveOtp': value['haveOtp'],
    };
=======
  return {
    vaultId: value['vaultId'],
    service: value['service'],
    website: value['website'],
    username: value['username'],
    password: value['password'],
    otpCode: value['otpCode'],
    favorite: value['favorite'],
    haveOtp: value['haveOtp'],
  };
>>>>>>> dev
}
