/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordCreateDto
 */
export interface PasswordCreateDto {
<<<<<<< HEAD
    /**
     * Vault ID of the vault you belong to
     * @type {string}
     * @memberof PasswordCreateDto
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordCreateDto
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordCreateDto
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordCreateDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordCreateDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordCreateDto
     */
    otpCode: string;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordCreateDto
     */
    favorite: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordCreateDto
     */
    haveOtp: boolean;
=======
  /**
   * Vault ID of the vault you belong to
   * @type {string}
   * @memberof PasswordCreateDto
   */
  vaultId: string;
  /**
   *
   * @type {string}
   * @memberof PasswordCreateDto
   */
  service: string;
  /**
   *
   * @type {string}
   * @memberof PasswordCreateDto
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordCreateDto
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof PasswordCreateDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof PasswordCreateDto
   */
  otpCode: string;
  /**
   *
   * @type {boolean}
   * @memberof PasswordCreateDto
   */
  favorite: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PasswordCreateDto
   */
  haveOtp: boolean;
>>>>>>> dev
}

/**
 * Check if a given object implements the PasswordCreateDto interface.
 */
export function instanceOfPasswordCreateDto(value: object): value is PasswordCreateDto {
<<<<<<< HEAD
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
    if (!('favorite' in value) || value['favorite'] === undefined) return false;
    if (!('haveOtp' in value) || value['haveOtp'] === undefined) return false;
    return true;
=======
  if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
  if (!('service' in value) || value['service'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
  if (!('favorite' in value) || value['favorite'] === undefined) return false;
  if (!('haveOtp' in value) || value['haveOtp'] === undefined) return false;
  return true;
>>>>>>> dev
}

export function PasswordCreateDtoFromJSON(json: any): PasswordCreateDto {
  return PasswordCreateDtoFromJSONTyped(json, false);
}

<<<<<<< HEAD
export function PasswordCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vaultId'],
        'service': json['service'],
        'website': json['website'] == null ? undefined : json['website'],
        'username': json['username'],
        'password': json['password'],
        'otpCode': json['otpCode'],
        'favorite': json['favorite'],
        'haveOtp': json['haveOtp'],
    };
=======
export function PasswordCreateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PasswordCreateDto {
  if (json == null) {
    return json;
  }
  return {
    vaultId: json['vaultId'],
    service: json['service'],
    website: json['website'] == null ? undefined : json['website'],
    username: json['username'],
    password: json['password'],
    otpCode: json['otpCode'],
    favorite: json['favorite'],
    haveOtp: json['haveOtp'],
  };
>>>>>>> dev
}

export function PasswordCreateDtoToJSON(json: any): PasswordCreateDto {
  return PasswordCreateDtoToJSONTyped(json, false);
}

export function PasswordCreateDtoToJSONTyped(
  value?: PasswordCreateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

<<<<<<< HEAD
    return {
        
        'vaultId': value['vaultId'],
        'service': value['service'],
        'website': value['website'],
        'username': value['username'],
        'password': value['password'],
        'otpCode': value['otpCode'],
        'favorite': value['favorite'],
        'haveOtp': value['haveOtp'],
    };
=======
  return {
    vaultId: value['vaultId'],
    service: value['service'],
    website: value['website'],
    username: value['username'],
    password: value['password'],
    otpCode: value['otpCode'],
    favorite: value['favorite'],
    haveOtp: value['haveOtp'],
  };
>>>>>>> dev
}
