/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordResponseDto
 */
export interface PasswordResponseDto {
  /**
   * Vault ID of the vault you belong to
   * @type {string}
   * @memberof PasswordResponseDto
   */
  vaultId: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  service: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  otpCode: string;
  /**
   *
   * @type {boolean}
   * @memberof PasswordResponseDto
   */
  favorite: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PasswordResponseDto
   */
  haveOtp: boolean;
  /**
   *
   * @type {string}
   * @memberof PasswordResponseDto
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof PasswordResponseDto
   */
  creationDate: Date;
  /**
   *
   * @type {Date}
   * @memberof PasswordResponseDto
   */
  modifiedDate: Date;
}

/**
 * Check if a given object implements the PasswordResponseDto interface.
 */
export function instanceOfPasswordResponseDto(value: object): value is PasswordResponseDto {
  if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
  if (!('service' in value) || value['service'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('otpCode' in value) || value['otpCode'] === undefined) return false;
  if (!('favorite' in value) || value['favorite'] === undefined) return false;
  if (!('haveOtp' in value) || value['haveOtp'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
  if (!('modifiedDate' in value) || value['modifiedDate'] === undefined) return false;
  return true;
}

export function PasswordResponseDtoFromJSON(json: any): PasswordResponseDto {
  return PasswordResponseDtoFromJSONTyped(json, false);
}

export function PasswordResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PasswordResponseDto {
  if (json == null) {
    return json;
  }
  return {
    vaultId: json['vaultId'],
    service: json['service'],
    website: json['website'] == null ? undefined : json['website'],
    username: json['username'],
    password: json['password'],
    otpCode: json['otpCode'],
    favorite: json['favorite'],
    haveOtp: json['haveOtp'],
    id: json['id'],
    creationDate: new Date(json['creationDate']),
    modifiedDate: new Date(json['modifiedDate']),
  };
}

export function PasswordResponseDtoToJSON(json: any): PasswordResponseDto {
  return PasswordResponseDtoToJSONTyped(json, false);
}

export function PasswordResponseDtoToJSONTyped(
  value?: PasswordResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    vaultId: value['vaultId'],
    service: value['service'],
    website: value['website'],
    username: value['username'],
    password: value['password'],
    otpCode: value['otpCode'],
    favorite: value['favorite'],
    haveOtp: value['haveOtp'],
    id: value['id'],
    creationDate: value['creationDate'].toISOString(),
    modifiedDate: value['modifiedDate'].toISOString(),
  };
}
