/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordsControllerUpdateFavoriteRequest
 */
export interface PasswordsControllerUpdateFavoriteRequest {
  /**
   *
   * @type {boolean}
   * @memberof PasswordsControllerUpdateFavoriteRequest
   */
  favorite?: boolean;
}

/**
 * Check if a given object implements the PasswordsControllerUpdateFavoriteRequest interface.
 */
export function instanceOfPasswordsControllerUpdateFavoriteRequest(
  value: object,
): value is PasswordsControllerUpdateFavoriteRequest {
  return true;
}

export function PasswordsControllerUpdateFavoriteRequestFromJSON(
  json: any,
): PasswordsControllerUpdateFavoriteRequest {
  return PasswordsControllerUpdateFavoriteRequestFromJSONTyped(json, false);
}

export function PasswordsControllerUpdateFavoriteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PasswordsControllerUpdateFavoriteRequest {
  if (json == null) {
    return json;
  }
  return {
    favorite: json['favorite'] == null ? undefined : json['favorite'],
  };
}

export function PasswordsControllerUpdateFavoriteRequestToJSON(
  json: any,
): PasswordsControllerUpdateFavoriteRequest {
  return PasswordsControllerUpdateFavoriteRequestToJSONTyped(json, false);
}

export function PasswordsControllerUpdateFavoriteRequestToJSONTyped(
  value?: PasswordsControllerUpdateFavoriteRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    favorite: value['favorite'],
  };
}
