/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserCreateDto
 */
export interface UserCreateDto {
  /**
   *
   * @type {string}
   * @memberof UserCreateDto
   */
  username: string;
  /**
   * Must contain at least 8 characters, one uppercase letter and one number
   * @type {string}
   * @memberof UserCreateDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof UserCreateDto
   */
  email: string;
}

/**
 * Check if a given object implements the UserCreateDto interface.
 */
export function instanceOfUserCreateDto(value: object): value is UserCreateDto {
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  return true;
}

export function UserCreateDtoFromJSON(json: any): UserCreateDto {
  return UserCreateDtoFromJSONTyped(json, false);
}

export function UserCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateDto {
  if (json == null) {
    return json;
  }
  return {
    username: json['username'],
    password: json['password'],
    email: json['email'],
  };
}

export function UserCreateDtoToJSON(json: any): UserCreateDto {
  return UserCreateDtoToJSONTyped(json, false);
}

export function UserCreateDtoToJSONTyped(
  value?: UserCreateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    username: value['username'],
    password: value['password'],
    email: value['email'],
  };
}
