/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VaultCreateDto
 */
export interface VaultCreateDto {
    /**
     * The name of the vault
     * @type {string}
     * @memberof VaultCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VaultCreateDto
     */
    description?: string;
    /**
     * Color identifier in HEX format
     * @type {string}
     * @memberof VaultCreateDto
     */
    color?: string;
}

/**
 * Check if a given object implements the VaultCreateDto interface.
 */
export function instanceOfVaultCreateDto(value: object): value is VaultCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function VaultCreateDtoFromJSON(json: any): VaultCreateDto {
    return VaultCreateDtoFromJSONTyped(json, false);
}

export function VaultCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VaultCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function VaultCreateDtoToJSON(json: any): VaultCreateDto {
    return VaultCreateDtoToJSONTyped(json, false);
}

export function VaultCreateDtoToJSONTyped(value?: VaultCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
    };
}

