/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VaultResponseDto
 */
export interface VaultResponseDto {
    /**
     * 
     * @type {string}
     * @memberof VaultResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VaultResponseDto
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof VaultResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VaultResponseDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof VaultResponseDto
     */
    color: string;
}

/**
 * Check if a given object implements the VaultResponseDto interface.
 */
export function instanceOfVaultResponseDto(value: object): value is VaultResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function VaultResponseDtoFromJSON(json: any): VaultResponseDto {
    return VaultResponseDtoFromJSONTyped(json, false);
}

export function VaultResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VaultResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerId': json['ownerId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'],
    };
}

export function VaultResponseDtoToJSON(json: any): VaultResponseDto {
    return VaultResponseDtoToJSONTyped(json, false);
}

export function VaultResponseDtoToJSONTyped(value?: VaultResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerId': value['ownerId'],
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
    };
}

