/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * Password manager APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VaultUpdateDto
 */
export interface VaultUpdateDto {
  /**
   * The name of the vault
   * @type {string}
   * @memberof VaultUpdateDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof VaultUpdateDto
   */
  description?: string;
  /**
   * Color identifier in HEX format
   * @type {string}
   * @memberof VaultUpdateDto
   */
  color?: string;
}

/**
 * Check if a given object implements the VaultUpdateDto interface.
 */
export function instanceOfVaultUpdateDto(value: object): value is VaultUpdateDto {
  return true;
}

export function VaultUpdateDtoFromJSON(json: any): VaultUpdateDto {
  return VaultUpdateDtoFromJSONTyped(json, false);
}

export function VaultUpdateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VaultUpdateDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    color: json['color'] == null ? undefined : json['color'],
  };
}

export function VaultUpdateDtoToJSON(json: any): VaultUpdateDto {
  return VaultUpdateDtoToJSONTyped(json, false);
}

export function VaultUpdateDtoToJSONTyped(
  value?: VaultUpdateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    description: value['description'],
    color: value['color'],
  };
}
