import ScanScreen from '@/app/scan';
import { act, fireEvent, render, screen } from '@testing-library/react-native';
import { useCameraPermissions } from 'expo-camera';
import { useRouter } from 'expo-router';
import React from 'react';
import { QrCodeService } from 'shared-password-manager/utils';

jest.mock('expo-router', () => ({
  useRouter: jest.fn(),
}));

jest.mock('expo-camera', () => {
  const { View } = require('react-native');
  return {
    useCameraPermissions: jest.fn(),
    CameraView: (props: any) => <View testID="camera-view" {...props} />,
  };
});

jest.mock('shared-password-manager/utils', () => {
  const actualUtils = jest.requireActual('shared-password-manager/utils');
  return {
    ...actualUtils,
    QrCodeService: {
      parseAndValidate: jest.fn(),
    },
  };
});

jest.mock('lucide-react-native', () => {
  const { View } = require('react-native');
  return {
    ScanLineIcon: () => <View testID="icon-scan-line" />,
    ArrowLeftIcon: () => <View testID="icon-arrow-left" />,
  };
});

describe('ScanScreen Component', () => {
  const mockPush = jest.fn();
  const mockBack = jest.fn();
  const mockRequestPermission = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    jest.useFakeTimers();

    (useRouter as jest.Mock).mockReturnValue({
      push: mockPush,
      back: mockBack,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
    jest.restoreAllMocks();
  });

  test('renders an empty background while checking for permissions', async () => {
    (useCameraPermissions as jest.Mock).mockReturnValue([null, mockRequestPermission]);

    await render(<ScanScreen />);

    expect(screen.queryByTestId('camera-view')).toBeNull();
  });

  test('renders the PermissionView when camera permission is denied', async () => {
    (useCameraPermissions as jest.Mock).mockReturnValue([
      { granted: false },
      mockRequestPermission,
    ]);

    await render(<ScanScreen />);

    expect(
      screen.getByText('We need permission to use the camera to scan the QR Code'),
    ).toBeOnTheScreen();
    expect(screen.queryByTestId('camera-view')).toBeNull();
  });

  test('renders the CameraView and overlay when permission is granted', async () => {
    (useCameraPermissions as jest.Mock).mockReturnValue([{ granted: true }, mockRequestPermission]);

    await render(<ScanScreen />);

    expect(screen.getByTestId('camera-view')).toBeOnTheScreen();
    expect(screen.getByText('Frame the QR Code generated by the site')).toBeOnTheScreen();
    expect(screen.getByRole('button', { name: 'Go back' })).toBeOnTheScreen();
  });

  test('navigates back when the float back button is pressed', async () => {
    (useCameraPermissions as jest.Mock).mockReturnValue([{ granted: true }, mockRequestPermission]);
    await render(<ScanScreen />);

    const backButton = screen.getByRole('button', { name: 'Go back' });
    await fireEvent.press(backButton);

    expect(mockBack).toHaveBeenCalledTimes(1);
  });

  test('processes a valid QR code and navigates to the details screen', async () => {
    (useCameraPermissions as jest.Mock).mockReturnValue([{ granted: true }, mockRequestPermission]);

    const validParsedData = { id: '123', name: 'Test', username: 'user', password: 'pwd' };
    (QrCodeService.parseAndValidate as jest.Mock).mockReturnValue(validParsedData);

    await render(<ScanScreen />);

    const camera = screen.getByTestId('camera-view');
    await fireEvent(camera, 'barcodeScanned', { data: '{"valid":"json"}' });

    expect(QrCodeService.parseAndValidate).toHaveBeenCalledWith('{"valid":"json"}');
    expect(mockPush).toHaveBeenCalledWith({
      pathname: '/details',
      params: { qrData: JSON.stringify(validParsedData) },
    });
  });

  test('shows an alert and reactivates the scanner after a delay if the QR is invalid', async () => {
    global.alert = jest.fn();
    (useCameraPermissions as jest.Mock).mockReturnValue([{ granted: true }, mockRequestPermission]);

    (QrCodeService.parseAndValidate as jest.Mock).mockImplementation(() => {
      throw new Error('Invalid QR Code.');
    });

    await render(<ScanScreen />);

    const camera = screen.getByTestId('camera-view');
    await fireEvent(camera, 'barcodeScanned', { data: 'invalid-string' });

    expect(global.alert).toHaveBeenCalledWith('Invalid QR Code.');
    expect(mockPush).not.toHaveBeenCalled();
    expect(camera.props.onBarcodeScanned).toBeUndefined();

    await act(() => {
      jest.advanceTimersByTime(2000);
    });

    const updatedCamera = screen.getByTestId('camera-view');
    expect(updatedCamera.props.onBarcodeScanned).toBeDefined();

    (global.alert as jest.Mock).mockClear();
  });
});
